### ISSUE TITLE
MikTeX 21.3 / pdflatex crashes sometimes after compiling LaTeX documents

### ISSUE THREAD

**Issue by petermelzner** [MiKTeX/miktex#765]
After updating MikTeX on Fedora 33 from version miktex-20.12-1.fc32.x86_64 to miktex-21.3-1.fc33.x86_64 MikTeX crashes on quite a lot of LaTeX files after compilation, for example this one:

```
\documentclass{book}
\usepackage{lipsum,graphicx,picinpar}

\begin{document}

    \begin{figwindow}[1,c,{
            \includegraphics[width=4.0cm,draft]{example-image.png}
        },{figwindow in a text}\label{fig}]
        \lipsum[1]
    \end{figwindow}

\end{document}
```

results in

```
$ pdflatex test.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3)
...
Output written on issue_38.pdf (1 page, 48716 bytes).
Transcript written on issue_38.log.
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

Another example:
```
\documentclass{book}
\usepackage{hyperref}
\begin{document}
\end{document}
```

```
$ pdflatex test.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3)
entering extended mode
(test.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/home/axel/.miktex/texmfs/install/tex/latex/base/book.cls
...
No pages of output.
Transcript written on test.log.
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

This happens only on some of my LaTeX files, for example when removing `\usepackage{hyperref}` in the example above it will compile without crash.

- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
[miktex-report.txt](https://github.com/MiKTeX/miktex/files/6215373/miktex-report.txt)
[test.zip](https://github.com/MiKTeX/miktex/files/6215374/test.zip)
[pdflatex.log](https://github.com/MiKTeX/miktex/files/6215377/pdflatex.log)

**Comment by petermelzner** [comment]
In the meantime I have upgraded from Fedora 33 to 34 and since there is no MikTeX repository for Fedora 34 yet I have compiled and installed MikTeX from the sources, but the problem remains. So I have compiled MikTeX with debug symbols and running pdflatex in gdb results in the following stack backtrace:

```
(gdb) r test
Starting program: /home/peter/bin/pdflatex test
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.33-5.fc34.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3)
entering extended mode
(test.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
[...]
No pages of output.
Transcript written on test.log.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000070 in ?? ()
(gdb) backtrace
#0  0x0000000000000070 in ?? ()
#1  0x00007ffff75b89c7 in log4cxx::LogManager::getLoggerLS(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /lib64/liblog4cxx.so.11
#2  0x00007ffff75b8abf in log4cxx::LogManager::getLogger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /lib64/liblog4cxx.so.11
#3  0x00007ffff75b8b32 in log4cxx::Logger::getLogger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /lib64/liblog4cxx.so.11
#4  0x00007ffff7e73eee in MiKTeX::App::Application::TraceInternal(MiKTeX::Trace::TraceCallback::TraceMessage const&) ()
   from /usr/local/bin/../lib64/libmiktex-app.so.6
#5  0x00007ffff7e769a0 in MiKTeX::App::Application::Trace(MiKTeX::Trace::TraceCallback::TraceMessage const&) ()
   from /usr/local/bin/../lib64/libmiktex-app.so.6
#6  0x00007ffff7c21c76 in TraceStreamImpl::Logger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MiKTeX::Trace::TraceLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/local/bin/../lib64/libmiktex-trace.so.5
#7  0x00007ffff7cb8d1c in MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::SessionImpl::CheckOpenFiles() () from /usr/local/bin/../lib64/libmiktex-core.so.23
#8  0x00007ffff7ce71bc in MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::SessionImpl::Uninitialize() () from /usr/local/bin/../lib64/libmiktex-core.so.23
#9  0x00007ffff7ce72e0 in MiKTeX::ABF3880A6239B84E87DC7E727A8BBFD4::SessionImpl::~SessionImpl() () from /usr/local/bin/../lib64/libmiktex-core.so.23
#10 0x00007ffff7d7be25 in MiKTeX::Locale::Translator::~Translator() () from /usr/local/bin/../lib64/libmiktex-loc.so.1
#11 0x00007ffff7d7be39 in MiKTeX::Locale::Translator::~Translator() () from /usr/local/bin/../lib64/libmiktex-loc.so.1
#12 0x00000000004116cd in PDFTEX::~PDFTEX() ()
#13 0x00007ffff76ddae7 in __run_exit_handlers () from /lib64/libc.so.6
#14 0x00007ffff76ddc90 in exit () from /lib64/libc.so.6
#15 0x00007ffff76c5b7c in __libc_start_main () from /lib64/libc.so.6
#16 0x0000000000410cee in _start ()
```

I hope this helps. If you need more information or if there is something I can debug additionally, please ask.

**Comment by edocevoli** [comment]
Thank you!
